/**
 * Content-Security-Policy readiness.
 *
 * Spektrum evaluates `{{expr}}` bindings at runtime, which needs `unsafe-eval` unless
 * the expressions are precompiled. A trading desk is exactly the kind of page that
 * should run under a strict CSP — it holds API keys in memory — so the seam is built
 * now rather than retrofitted: extract every expression from the HTML, hand them to
 * `spektrum/compile` at build time, and the runtime never evaluates a string.
 *
 * These functions are the extraction half; the compile step consumes them.
 */

/** Binding attributes whose values are expressions Spektrum evaluates. */
export const EXPRESSION_ATTRS = Object.freeze([
  'data-if',
  'data-each',
  'data-model',
  'data-value',
])

/**
 * Pull every `{{expr}}` out of a template.
 *
 * @param {string} html - template source.
 * @returns {string[]} unique expressions, in first-seen order.
 */
export function extractMustaches(html) {
  const source = String(html ?? '')
  const found = []

  for (const match of source.matchAll(/\{\{([^}]+)\}\}/g)) {
    const expr = match[1].trim()
    if (expr && !found.includes(expr)) found.push(expr)
  }
  return found
}

/**
 * Pull expressions out of binding attributes (`:attr="..."`, `data-if="..."`).
 *
 * @param {string} html - template source.
 * @returns {string[]} unique expressions, in first-seen order.
 */
export function extractAttrExpressions(html) {
  const source = String(html ?? '')
  const found = []
  const add = (expr) => {
    const trimmed = String(expr ?? '').trim()
    if (trimmed && !found.includes(trimmed)) found.push(trimmed)
  }

  // :attr="expr" — property bindings.
  for (const match of source.matchAll(/\s:([\w-]+)="([^"]*)"/g)) add(match[2])

  // data-if / data-each / data-model / data-value — structural and two-way bindings.
  for (const attr of EXPRESSION_ATTRS) {
    const re = new RegExp(`\\s${attr}="([^"]*)"`, 'g')
    for (const match of source.matchAll(re)) add(match[1])
  }
  return found
}

/**
 * Every expression a template asks the engine to evaluate.
 *
 * This is the exact set that must be precompiled for a strict-CSP build; anything missed
 * here would fail silently at runtime under `unsafe-eval`-free policy, which is why the
 * extraction is unit-tested rather than trusted.
 *
 * @param {string} html - template source.
 * @returns {string[]} unique expressions, mustaches first.
 */
export function collectExpressions(html) {
  const all = [...extractMustaches(html), ...extractAttrExpressions(html)]
  return [...new Set(all)]
}

/**
 * Render the precompile module a strict-CSP build loads before the engine runs.
 *
 * @param {string[]} expressions - what to precompile.
 * @returns {string} ES module source.
 */
export function renderPrecompileModule(expressions) {
  const list = Array.isArray(expressions) ? expressions : []
  const entries = list
    .map((expr) => `  precompile(${JSON.stringify(expr)}, (state) => (${expr}))`)
    .join('\n')

  return [
    "import { precompile } from 'spektrum'",
    '',
    '// Generated by scripts/compile-templates.mjs — do not edit.',
    '// Every runtime expression, compiled ahead of time so the engine never evaluates a',
    '// string and the desk can run under a CSP without unsafe-eval.',
    'export function registerCompiledExpressions() {',
    entries,
    `  return ${list.length}`,
    '}',
    '',
  ].join('\n')
}

/**
 * The policy a hardened build ships.
 *
 * `unsafe-eval` is absent by design. unpkg is allowed because the engine is loaded from
 * there; when that changes, this is the one place to update.
 *
 * @param {{reportOnly?: boolean}} [options] - report-only for a staged rollout.
 * @returns {{name: string, content: string}} meta tag name and content.
 */
export function cspMeta(options = {}) {
  const { reportOnly = false } = options

  const directives = [
    "default-src 'self'",
    "script-src 'self' https://unpkg.com",
    "style-src 'self' 'unsafe-inline'",
    // REST is same-origin now (the Node backend relays to the venues), so 'self' covers
    // it. The sockets stay direct — websockets are CORS-exempt — and every OKX universe
    // the desk can aim at is listed, or the region/demo switches would silently connect
    // to nothing.
    "connect-src 'self' https://unpkg.com" +
      ' wss://ws.okx.com wss://wspap.okx.com wss://wseea.okx.com wss://wseeapap.okx.com',
    "img-src 'self' data:",
    "object-src 'none'",
    "base-uri 'self'",
  ]

  return {
    name: reportOnly
      ? 'Content-Security-Policy-Report-Only'
      : 'Content-Security-Policy',
    content: directives.join('; '),
  }
}
